#!/bin/bash

# Sparky 1.0 2010-03-04
# Copyright (c) Mike Smullin <mike@smullindesign.com>
# Licensed under the MIT

# set defaults
SPARK_SRC_DIR="sparkup"
SPARK_DST_DIR="html"
SPARKUP="sparkup"

# load custom config
# to create your own custom config, copy the above two lines to 
# the following file, and change them to your liking.
. config.sh

echo ">>> Sparky is watching for changes. Press Ctrl-C to Stop."

# the loop
while true
do
  for f in $( cd $SPARK_SRC_DIR && find -type f -name "*.spark" )
  do
    in=$(echo "$SPARK_SRC_DIR/$f" | sed -r 's#/\./#/#g')
    out=$(echo "$SPARK_DST_DIR/$f" | sed -r 's#/\./#/#g' | sed -r 's/.spark$/.html/i')
    if [ $in -nt $out ]
    then
      echo ">>> Change detected to: $in"
      mkdir -p "$out" >/dev/null 2>&1
      rm -rf "$out" >/dev/null 2>&1
      cat "$in" | $SPARKUP > "$out"
      echo "overwrite $out"
    fi
  done
  sleep 1
done
